version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=luna-chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  tailwind:
    image: node:20-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npx tailwindcss -i ./static/css/main.css -o ./static/css/tailwind/output.css --watch"
    depends_on:
      - web


  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=luna-chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: